// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCv4Ehr3ZtxhhQJhdiNx1QxaBpNzk-ckHA',
    appId: '1:11097370396:web:3c549a42ff12ccd97654d9',
    messagingSenderId: '11097370396',
    projectId: 'movecar-65d1e',
    authDomain: 'movecar-65d1e.firebaseapp.com',
    storageBucket: 'movecar-65d1e.firebasestorage.app',
    measurementId: 'G-TKX05FEXCT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWKfrFahqbbHIPJaxWB-oYRZnc7zDk_DA',
    appId: '1:11097370396:android:d63f3831bf8066d27654d9',
    messagingSenderId: '11097370396',
    projectId: 'movecar-65d1e',
    storageBucket: 'movecar-65d1e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdFDwIuL93kkUQKXJOqKQgb6EpX7qRi-c',
    appId: '1:11097370396:ios:4d57eb16e7dfabc17654d9',
    messagingSenderId: '11097370396',
    projectId: 'movecar-65d1e',
    storageBucket: 'movecar-65d1e.firebasestorage.app',
    iosBundleId: 'com.example.convoyeurMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdFDwIuL93kkUQKXJOqKQgb6EpX7qRi-c',
    appId: '1:11097370396:ios:4d57eb16e7dfabc17654d9',
    messagingSenderId: '11097370396',
    projectId: 'movecar-65d1e',
    storageBucket: 'movecar-65d1e.firebasestorage.app',
    iosBundleId: 'com.example.convoyeurMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCv4Ehr3ZtxhhQJhdiNx1QxaBpNzk-ckHA',
    appId: '1:11097370396:web:4fc11906c595f82d7654d9',
    messagingSenderId: '11097370396',
    projectId: 'movecar-65d1e',
    authDomain: 'movecar-65d1e.firebaseapp.com',
    storageBucket: 'movecar-65d1e.firebasestorage.app',
    measurementId: 'G-R94P1F3HJ7',
  );
}
